# https://pre-commit.ci/
# Configuration for Continuous Integration service
ci:
  # Borrowed from NVDA repo
  # https://github.com/nvaccess/nvda
  # Can't run Windows scons scripts on Linux.
  # unit testing requires our python environment,
  # which cannot be configured with pre-commit.ci:
  # https://stackoverflow.com/questions/70778806/pre-commit-not-using-virtual-environment .
  # Can't run licenseCheck as it relies on telemetry,
  # which CI blocks.
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "Pre-commit auto-update"
  autofix_commit_msg: "Pre-commit auto-fix"

default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: v1.6.1
  hooks:
    - id: check-pre-commit-ci-config

- repo: meta
  hooks:
    # ensures that exclude directives apply to any file in the repository.
    - id: check-useless-excludes
    # ensures that the configured hooks apply to at least one file in the repository.
    - id: check-hooks-apply

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    # Prevents commits to certain branches
    - id: no-commit-to-branch
      args: ["--branch", "main"]
    # Checks that large files have not been added. Default cut-off for "large" files is 500kb.
    - id: check-added-large-files
      # POFiles and TTF fonts can't be made smaller
      exclude_types: ["pofile", "ttf"]
    # Checks python syntax
    - id: check-ast
    # Checks for filenames that will conflict on case insensitive filesystems (the majority of Windows filesystems, most of the time)
    - id: check-case-conflict
    # Checks for artifacts from resolving merge conflicts.
    - id: check-merge-conflict
    # Checks Python files for debug statements, such as python's breakpoint function, or those inserted by some IDEs.
    - id: debug-statements
    # Removes trailing whitespace.
    - id: trailing-whitespace
      types_or: [python, c, c++, batch, markdown]
    # Ensures all files end in 1 (and only 1) newline.
    - id: end-of-file-fixer
      types_or: [python, c, c++, batch, markdown]
    # Removes the UTF-8 BOM from files that have it.
    # See https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/codingStandards.md#encoding
    - id: fix-byte-order-marker
      types_or: [python, c, c++, batch, markdown]
    # Validates TOML files.
    - id: check-toml
    # Validates YAML files.
    - id: check-yaml
    # Ensures that links to lines in files under version control point to a particular commit.
    - id: check-vcs-permalinks
    # Avoids using reserved Windows filenames.
    - id: check-illegal-windows-names

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  # Ruff preserves indent/new-line formatting of function arguments, list items, and similar iterables,
  # if a trailing comma is added.
  # This adds a trailing comma to args/iterable items in case it was missed.
  - id: add-trailing-comma

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Matches Ruff version in requirements.
  rev: v0.8.1
  hooks:
    - id: ruff
      name: lint with ruff
      args: [ --fix ]
    - id: ruff-format
      name: format with ruff
