"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "*.pot",
    "translation": "clipContentsDesigner/addon/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "*.md",
    "translation": "clipContentsDesigner/addon/doc/%two_letters_code%/readme.xliff"
  },
]
