# Stub for AddonSettingsPanel and related controls
from typing import Any

class AddonSettingsPanel:
	setSeparatorEdit: "TextCtrl"
	addTextBeforeCheckBox: "CheckBox"
	confirmList: "CustomCheckListBox"
	confirmRequirementChoices: "Choice"
	formatChoices: "Choice"
	maxLengthEdit: "SelectOnFocusSpinCtrl"
	runOnInstallCheckBox: "CheckBox"
	restoreDefaultsButton: "Button"
	def onRestoreDefaults(self, evt: Any) -> None: ...
	def onSave(self) -> None: ...

class TextCtrl:
	def GetValue(self) -> str: ...
	def SetValue(self, value: str) -> None: ...

class CheckBox:
	def GetValue(self) -> bool: ...
	def SetValue(self, value: bool) -> None: ...

class CustomCheckListBox:
	CheckedItems: list[int]
	def IsChecked(self, index: int) -> bool: ...
	def Select(self, index: int) -> None: ...

class Choice:
	def GetSelection(self) -> int: ...
	def SetSelection(self, index: int) -> None: ...

class SelectOnFocusSpinCtrl:
	def GetValue(self) -> int: ...
	def SetValue(self, value: int) -> None: ...

class Button:
	def Bind(self, event: Any, handler: Any) -> None: ...

EVT_BUTTON: Any
