# Expanded stub for gui.nvdaControls
from typing import Any

class CustomCheckListBox:
    CheckedItems: list[int]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def IsChecked(self, index: int) -> bool: ...
    def Select(self, index: int) -> None: ...

class SelectOnFocusSpinCtrl:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def GetValue(self) -> int: ...
    def SetValue(self, value: int) -> None: ...
