# Expanded stub for guiHelper.BoxSizerHelper
from typing import Any, TypeVar

_T = TypeVar("_T")

class BoxSizerHelper:
	def __init__(self, parent: Any, sizer: Any = None) -> None: ...
	def addLabeledControl(__self, __labelText: str, __wxCtrlClass: type[_T], /, **kwargs: Any) -> _T: ...
	def addItem(__self, __item: _T, /, **keywordArgs: Any) -> _T: ...

class wxTextCtrl:
	def GetValue(self) -> str: ...
	def SetValue(self, value: str) -> None: ...

class wxCheckBox:
	def GetValue(self) -> bool: ...
	def SetValue(self, value: bool) -> None: ...

class wxButton:
	def Bind(self, event: Any, handler: Any) -> None: ...

class wxChoice:
	def GetSelection(self) -> int: ...
	def SetSelection(self, index: int) -> None: ...

class SelectOnFocusSpinCtrl:
	def GetValue(self) -> int: ...
	def SetValue(self, value: int) -> None: ...

EVT_BUTTON: Any
