# inputCore stub for NVDA add-on compatibility
from typing import Any

class manager:
    class userGestureMap:
        def add(self, gesture: str, module: str, className: str, scriptName: str) -> None: ...
        def remove(self, gesture: str, module: str, className: str, scriptName: str) -> None: ...
        def save(self) -> None: ...
