# inputCore stub for NVDA add-on compatibility

class manager:
	class userGestureMap:
		def add(self, gesture: str, module: str, className: str, scriptName: str) -> None: ...
		def remove(self, gesture: str, module: str, className: str, scriptName: str) -> None: ...
		def save(self) -> None: ...
