# Stub for inputCore.manager.userGestureMap methods

class userGestureMap:
	def add(__self, __gesture: str, __module: str, __className: str, __scriptName: str, /) -> None: ...
	def remove(__self, __gesture: str, __module: str, __className: str, __scriptName: str, /) -> None: ...
	def save(__self, /) -> None: ...
