# Stub for logHandler module
from typing import Any

class Logger:
	def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
	def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
	def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
	def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...

log: Logger
