class AddonSettingsPanel:
	setSeparatorEdit: wx.TextCtrl
	addTextBeforeCheckBox: wx.CheckBox
	confirmList: gui.nvdaControls.CustomCheckListBox
	confirmRequirementChoices: wx.Choice
	formatChoices: wx.Choice
	maxLengthEdit: gui.nvdaControls.SelectOnFocusSpinCtrl
	runOnInstallCheckBox: wx.CheckBox
	restoreDefaultsButton: wx.Button
	def onRestoreDefaults(self, evt: Any) -> None: ...
	def onSave(self) -> None: ...

# Stub file for NVDA runtime-provided objects

from typing import Any, Callable, Optional

# Common NVDA globals
_: Callable[[str], str]

class wx:
	class TextCtrl:
		def __init__(self, *args, **kwargs): ...
		def GetValue(self) -> str: ...
		def SetValue(self, value: str) -> None: ...

	class CheckBox:
		def __init__(self, parent: Any, label: Optional[str] = None): ...
		def GetValue(self) -> bool: ...
		def SetValue(self, value: bool) -> None: ...

	class Button:
		def __init__(self, parent: Any, label: Optional[str] = None): ...
		def Bind(self, event: Any, handler: Any) -> None: ...

	class Choice:
		def __init__(self, parent: Any, choices: list[str]): ...
		def GetSelection(self) -> int: ...
		def SetSelection(self, index: int) -> None: ...

	EVT_BUTTON: Any
	MessageBoxCaptionStr: str
	@staticmethod
	def CallAfter(func: Any, *args, **kwargs) -> None: ...
	@staticmethod
	def MessageBox(message: str, caption: Optional[str] = None, style: Optional[int] = None) -> int: ...

class gui:
	class nvdaControls:
		class CustomCheckListBox:
			CheckedItems: list[int]
			def __init__(self, *args, **kwargs): ...
			def IsChecked(self, index: int) -> bool: ...
			def Select(self, index: int) -> None: ...

		class SelectOnFocusSpinCtrl:
			def __init__(self, *args, **kwargs): ...
			def GetValue(self) -> int: ...
			def SetValue(self, value: int) -> None: ...

	class mainFrame:
		Handle: Any
		@staticmethod
		def popupSettingsDialog(dialogClass: Any, panelClass: Any) -> None: ...

	class blockAction:
		class Context:
			MODAL_DIALOG_OPEN: Any

		@staticmethod
		def when(context: Any) -> Callable: ...

class guiHelper:
	class BoxSizerHelper:
		def __init__(self, parent: Any, sizer: Any = None): ...
		def addLabeledControl(self, labelText: str, wxCtrlClass: Any, **kwargs: Any) -> Any: ...
		def addItem(self, item: Any, **keywordArgs: Any) -> Any: ...

class addonHandler:
	@staticmethod
	def getCodeAddonPath() -> str: ...
	@staticmethod
	def initTranslation() -> None: ...

class config:
	class conf:
		spec: dict[str, Any]
		def __getitem__(self, key: str) -> dict[str, Any]: ...
		def getConfigValidation(self, keyPath: Any) -> Any: ...
		def save(self) -> None: ...

class scriptHandler: ...
