# nvdaControls stub for NVDA add-on compatibility
from typing import Any


from typing import Any, List

class CustomCheckListBox:
    CheckedItems: List[int]
    def __init__(self, *args, **kwargs): ...
    def IsChecked(self, index: int) -> bool: ...
    def Select(self, index: int) -> None: ...

class SelectOnFocusSpinCtrl:
    def __init__(self, *args, **kwargs): ...
    def GetValue(self) -> int: ...
    def SetValue(self, value: int) -> None: ...
