# Stub file for NVDA runtime-provided objects

from typing import Any, Callable

# Common NVDA globals
_: Callable[[str], str]

class wx:
    class TextCtrl:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def GetValue(self) -> str: ...
        def SetValue(self, value: str) -> None: ...
    class CheckBox:
        def __init__(self, parent: Any, label: str | None = None) -> None: ...
        def GetValue(self) -> bool: ...
        def SetValue(self, value: bool) -> None: ...
    class Button:
        def __init__(self, parent: Any, label: str | None = None) -> None: ...
        def Bind(self, event: Any, handler: Any) -> None: ...
    class Choice:
        def __init__(self, parent: Any, choices: list[str]) -> None: ...
        def GetSelection(self) -> int: ...
        def SetSelection(self, index: int) -> None: ...
    EVT_BUTTON: Any
    MessageBoxCaptionStr: str
    @staticmethod
    def CallAfter(func: Any, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def MessageBox(message: str, caption: str | None = None, style: int | None = None) -> int: ...

class gui:
    class nvdaControls:
        class CustomCheckListBox:
            CheckedItems: list[int]
            def __init__(self, *args: Any, **kwargs: Any) -> None: ...
            def IsChecked(self, index: int) -> bool: ...
            def Select(self, index: int) -> None: ...
        class SelectOnFocusSpinCtrl:
            def __init__(self, *args: Any, **kwargs: Any) -> None: ...
            def GetValue(self) -> int: ...
            def SetValue(self, value: int) -> None: ...
    class mainFrame:
        Handle: Any
        @staticmethod
        def popupSettingsDialog(dialogClass: Any, panelClass: Any) -> None: ...
    class blockAction:
        class Context:
            MODAL_DIALOG_OPEN: Any
        @staticmethod
        def when(context: Any) -> Callable[..., Any]: ...

class guiHelper:
    class BoxSizerHelper:
        def __init__(self, parent: Any, sizer: Any = None) -> None: ...
        def addLabeledControl(self, labelText: str, wxCtrlClass: Any, **kwargs: Any) -> Any: ...
        def addItem(self, item: Any, **keywordArgs: Any) -> Any: ...

class addonHandler:
    @staticmethod
    def getCodeAddonPath() -> str: ...
    @staticmethod
    def initTranslation() -> None: ...

class config:
    class conf:
        spec: dict[str, Any]
        def __getitem__(self, key: str) -> dict[str, Any]: ...
        def getConfigValidation(self, keyPath: Any) -> Any: ...
        def save(self) -> None: ...

class scriptHandler:
    ...
