from typing import Any

class SettingsPanel:
    title: str
    def makeSettings(self, sizer: Any) -> None: ...
    def onRestoreDefaults(self, evt: Any) -> None: ...
    def onSave(self) -> None: ...
