from typing import Any

class SettingsPanel:
    title: str
    def makeSettings(__self, __sizer: Any, /) -> None: ...
    def onRestoreDefaults(self, evt: Any) -> None: ...
    def onSave(__self, /) -> None: ...
