# Stub for winUser module
from typing import Any, ContextManager

def getForegroundWindow() -> int: ...
def getWindowThreadProcessID(window: int) -> tuple[int, int]: ...
def getKeyboardLayout(threadID: int) -> int: ...
def openClipboard(__handle: int, /) -> ContextManager[Any]: ...
def emptyClipboard() -> None: ...

class windll:
    class user32:
        @staticmethod
        def EnumClipboardFormats(format: int) -> int: ...
