# wxPython stub for NVDA add-on compatibility
from typing import Any, Callable, TypeVar

_T = TypeVar('_T')

class TextCtrl:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def GetValue(self) -> str: ...
    def SetValue(self, value: str) -> None: ...

class CheckBox:
    def __init__(self, parent: Any, label: str | None = None) -> None: ...
    def GetValue(self) -> bool: ...
    def SetValue(self, value: bool) -> None: ...

class Button:
    def __init__(self, parent: Any, label: str | None = None) -> None: ...
    def Bind(self, event: Any, handler: Any) -> None: ...

class Choice:
    def __init__(self, parent: Any, choices: list[str]) -> None: ...
    def GetSelection(self) -> int: ...
    def SetSelection(self, index: int) -> None: ...

EVT_BUTTON: Any
MessageBoxCaptionStr: str

def CallAfter(func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...

def MessageBox(message: str, caption: str | None = None, style: int | None = None) -> int: ...
