# wxPython stub for NVDA add-on compatibility
from typing import Any, Optional

class TextCtrl:
    def __init__(self, *args, **kwargs): ...
    def GetValue(self) -> str: ...
    def SetValue(self, value: str) -> None: ...

class CheckBox:
    def __init__(self, parent: Any, label: Optional[str] = None): ...
    def GetValue(self) -> bool: ...
    def SetValue(self, value: bool) -> None: ...

class Button:
    def __init__(self, parent: Any, label: Optional[str] = None): ...
    def Bind(self, event: Any, handler: Any) -> None: ...

class Choice:
    def __init__(self, parent: Any, choices: list[str]): ...
    def GetSelection(self) -> int: ...
    def SetSelection(self, index: int) -> None: ...

EVT_BUTTON: Any
MessageBoxCaptionStr: str

def CallAfter(func: Any, *args, **kwargs) -> None: ...

def MessageBox(message: str, caption: Optional[str] = None, style: Optional[int] = None) -> int: ...
