# Stub for gui module
from typing import Any, Callable

class nvdaControls:
    class CustomCheckListBox:
        CheckedItems: list[int]
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def IsChecked(self, index: int) -> bool: ...
        def Select(self, index: int) -> None: ...
    class SelectOnFocusSpinCtrl:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def GetValue(self) -> int: ...
        def SetValue(self, value: int) -> None: ...

class mainFrame:
    Handle: int
    @staticmethod
    def popupSettingsDialog(__dialogClass: Any, __panelClass: Any, /) -> None: ...

class blockAction:
    class Context:
        MODAL_DIALOG_OPEN: Any
    @staticmethod
    def when(context: Any) -> Callable[..., Any]: ...
