name: pre-release

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 6'

jobs:
  pre-release:
    uses: nvdaes/nvdaAddonWorkflows/.github/workflows/automaticRelease.yaml@main
    