name: Store  

on:
  release:
    types: [published]

jobs:
  store:
    runs-on: windows-latest
    steps:
      
    - name: Checkout validation repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore-validation
        submodules: true
        path: validation
    - name: Checkout datastore repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore
        path: store
    
    - name: Download add-on
      run: |
        curl --location --output addon.nvda-addon ${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ github.event.repository.name }}-${{ github.event.release.tag-name }}.nvda-addon
